"use client";
import {useEffect,useState} from "react";
import {Activity,BarChart3,CalendarDays,ChevronRight,Copy,Disc3,Flame,Home,Lightbulb,ListMusic,Menu,Music2,Plus,Radio,Rocket,Search,Sparkles,TrendingUp,X} from "lucide-react";
import ProjectStudio from "./project-studio";

type Project={id:number;title:string;genre:string;stage:string;score:number};
const seed:Project[]=[
 {id:1,title:"Eindhoven From The Sky",genre:"Dutch stadium pop",stage:"Suno versions",score:86},
 {id:2,title:"Ena Chkounek",genre:"Tunisian urban",stage:"Release ready",score:92},
 {id:3,title:"Midnight Signal",genre:"Afro electronic",stage:"Lyrics",score:74},
];
const nav=[["home","Command",Home],["trends","Trend radar",Flame],["projects","Song projects",ListMusic],["suno","Suno builder",Sparkles],["calendar","Release plan",CalendarDays],["analytics","Analytics",BarChart3]] as const;
const trends=[{name:"NL football chants",market:"Netherlands",lift:"+38%",score:91},{name:"Tunisian summer rap",market:"Tunisia · France",lift:"+24%",score:84},{name:"Arabic wedding hooks",market:"MENA · Europe",lift:"+17%",score:78}];

export default function Page(){
 const [tab,setTab]=useState("home"),[projects,setProjects]=useState<Project[]>(seed),[modal,setModal]=useState(false),[mobile,setMobile]=useState(false),[title,setTitle]=useState(""),[copied]=useState(false),[sync,setSync]=useState("Cloud ready"),[selected,setSelected]=useState<Project|null>(null);
 useEffect(()=>{fetch("/api/projects").then(r=>r.ok?r.json():Promise.reject()).then(data=>{if(data.projects?.length)setProjects(data.projects);setSync("Cloud synced")}).catch(()=>{const x=localStorage.getItem("amir-projects");if(x)setProjects(JSON.parse(x));setSync("Device storage")})},[]);
 const add=async()=>{if(!title.trim())return;const draft={id:Date.now(),title,genre:"Tunisian urban",stage:"Idea",score:65};const next=[draft,...projects];setProjects(next);localStorage.setItem("amir-projects",JSON.stringify(next));setTitle("");setModal(false);setTab("projects");try{const r=await fetch("/api/projects",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title:draft.title,genre:draft.genre})});if(r.ok){const {project}=await r.json();setProjects(current=>current.map(p=>p.id===draft.id?project:p));setSync("Cloud synced")}}catch{setSync("Device storage")}};
 return <main className="shell">
  <aside className={mobile?"side open":"side"}><button className="close" onClick={()=>setMobile(false)}><X/></button><div className="brand"><b><Music2/></b><div><strong>AMIR</strong><span>MUSIC OS</span></div></div><small className="label">WORKSPACE</small><nav>{nav.map(([id,name,Icon])=><button key={id} className={tab===id?"active":""} onClick={()=>{setTab(id);setMobile(false)}}><Icon/><span>{name}</span>{tab===id&&<i/>}</button>)}</nav><div className="status"><span><Radio/> Studio status</span><b><i/>Ready to create</b><small>{sync}</small></div><div className="profile"><b>AH</b><div><strong>Amir Hamrouni</strong><span>Independent artist</span></div></div></aside>
  <section className="work"><header><button className="hamb" onClick={()=>setMobile(true)}><Menu/></button><div className="crumb">AMIR MUSIC OS <ChevronRight/> <b>{nav.find(n=>n[0]===tab)?.[1]}</b></div><div className="actions"><button className="search"><Search/>Search anything <kbd>⌘K</kbd></button><button className="primary" onClick={()=>setModal(true)}><Plus/>New song</button></div></header>
   <div className="content">
    {selected&&<ProjectStudio project={selected} onBack={()=>setSelected(null)}/>} 
    {!selected&&<>
    {tab==="home"&&<Dashboard projects={projects} onNew={()=>setModal(true)} go={setTab}/>} 
    {tab==="trends"&&<Trends choose={(x)=>{setTitle(x);setModal(true)}}/>}
    {tab==="projects"&&<Projects items={projects} onNew={()=>setModal(true)} onOpen={setSelected}/>} 
    {tab==="suno"&&<Suno copied={copied}/>}
    {tab==="calendar"&&<ReleasePlan/>}{tab==="analytics"&&<Analytics/>}
    </>}
   </div>
  </section>
  {modal&&<div className="backdrop" onMouseDown={()=>setModal(false)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="x" onClick={()=>setModal(false)}><X/></button><small className="label">NEW CREATIVE PROJECT</small><h2>Start with the signal.</h2><p>Capture the idea now. Shape the sound inside your private studio.</p><label>Song title<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} onKeyDown={e=>e.key==="Enter"&&add()} placeholder="Night over Eindhoven"/></label><label>Sound direction<select><option>Tunisian urban</option><option>Dutch stadium pop</option><option>Afro electronic</option></select></label><button className="primary wide" onClick={add}>Create project <ChevronRight/></button></div></div>}
 </main>
}
const prompt="Modern Tunisian urban pop-rap, emotional male vocal, memorable melodic chorus, warm oud accents, crisp North African percussion, deep controlled bass, 96 BPM, radio-ready production, clear Tunisian pronunciation, dynamic verses, explosive final chorus.\n\nAvoid: excessive autotune, comedy vocals, distorted mix, long instrumental intro, random ad-libs.";

function Title({tag,title,text,action}:{tag:string,title:string,text:string,action?:React.ReactNode}){return <div className="page-title"><div><small className="label">{tag}</small><h1>{title}</h1><p>{text}</p></div>{action}</div>}
function Dashboard({projects,onNew,go}:{projects:Project[],onNew:()=>void,go:(x:string)=>void}){return <><section className="hero"><div><small className="label">SATURDAY · CREATIVE CONTROL</small><h1>Make the next song<br/><em>impossible to skip.</em></h1><p>Your private system for turning signals into releases—and releases into decisions.</p></div><button className="primary launch" onClick={onNew}><Sparkles/>Start a new song</button></section><div className="metrics"><Metric icon={<Disc3/>} name="Active projects" value={String(projects.length).padStart(2,"0")} note="One needs your decision"/><Metric icon={<Rocket/>} name="Release ready" value={String(projects.filter(x=>x.stage.includes("ready")).length).padStart(2,"0")} note="Assets prepared"/><Metric icon={<Activity/>} name="Average score" value={String(Math.round(projects.reduce((a,b)=>a+b.score,0)/projects.length))} note="Strong creative signal"/><Metric icon={<TrendingUp/>} name="7-day momentum" value="+24%" note="Across tracked content"/></div><div className="cols"><section className="panel pipeline"><div className="panel-head"><div><small className="label">IN MOTION</small><h2>Song pipeline</h2></div><button onClick={()=>go("projects")}>View all <ChevronRight/></button></div>{projects.slice(0,3).map((p,i)=><div className="song" key={p.id}><small>0{i+1}</small><b className="cover"><Disc3/></b><div><strong>{p.title}</strong><span>{p.genre}</span></div><i>{p.stage}</i><b>{p.score}</b></div>)}</section><section className="panel signal"><Activity/><small className="label">SIGNAL OF THE DAY</small><h2>Dutch football chants are accelerating.</h2><p>Search interest and short-form audio activity are rising ahead of the next fixture window.</p><div><b>91<small>OPPORTUNITY</small></b><b>+38%<small>7-DAY LIFT</small></b></div><button onClick={()=>go("trends")}>Open trend radar <ChevronRight/></button></section></div></>}
function Metric({icon,name,value,note}:{icon:React.ReactNode,name:string,value:string,note:string}){return <article><span>{icon}{name}</span><b>{value}</b><small>{note}</small></article>}
function Trends({choose}:{choose:(x:string)=>void}){return <><Title tag="DISCOVERY" title="Trend radar" text="Shortlist signals worth turning into an original sound."/><div className="trend-grid">{trends.map((t,i)=><article className="trend" key={t.name}><div className={`art a${i}`}><TrendingUp/><b>{t.lift}</b></div><small>{t.market}</small><h2>{t.name}</h2><div><b>{t.score}<small>OPPORTUNITY</small></b><button onClick={()=>choose(t.name)}>Create from signal <Plus/></button></div></article>)}</div><div className="panel note"><Lightbulb/><div><b>Human signal, not blind automation.</b><p>Trends provide context. Your angle, writing and final selection keep every release original.</p></div></div></>}
function Projects({items,onNew,onOpen}:{items:Project[],onNew:()=>void,onOpen:(p:Project)=>void}){return <><Title tag="CATALOG" title="Song projects" text="Every idea, version and release decision in one place." action={<button className="primary" onClick={onNew}><Plus/>New project</button>}/><div className="table"><div className="thead"><span>PROJECT</span><span>STAGE</span><span>SCORE</span></div>{items.map((p,i)=><button className="trow project-open" key={p.id} onClick={()=>onOpen(p)}><div><b>{String(i+1).padStart(2,"0")}</b><span><strong>{p.title}</strong><small>{p.genre}</small></span></div><i>{p.stage}</i><strong>{p.score}/100</strong></button>)}</div></>}
function Suno({copied}:{copied:boolean}){
 const [direction,setDirection]=useState("A bold Tunisian track about ambition, distance and refusing to disappear."),[language,setLanguage]=useState("Tunisian"),[vocal,setVocal]=useState("Emotional male"),[hook,setHook]=useState("Natlaa lfou9, hatta ken ellil twil"),[result,setResult]=useState<{title:string;lyrics:string;stylePrompt:string;excludedStyles:string;hooks:string[];rationale:string}|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const generate=async()=>{setLoading(true);setError("");try{const r=await fetch("/api/generate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({direction,language,vocal,hook})});const data=await r.json();if(!r.ok)throw new Error(data.error||"Generation failed");setResult(data.package)}catch(e){setError(e instanceof Error?e.message:"Generation failed")}finally{setLoading(false)}};
 const output=result?.stylePrompt||prompt;
 return <><Title tag="PRODUCTION" title="Suno builder" text="Build a precise sound package, then move it to Suno with one copy."/><div className="studio"><section className="panel form"><small className="label">01 · SOUND BRIEF</small><label>Creative direction<textarea value={direction} onChange={e=>setDirection(e.target.value)}/></label><div><label>Language<select value={language} onChange={e=>setLanguage(e.target.value)}><option>Tunisian</option><option>Dutch</option><option>English</option><option>Arabic</option><option>French</option></select></label><label>Vocal<select value={vocal} onChange={e=>setVocal(e.target.value)}><option>Emotional male</option><option>Powerful female</option><option>Duet</option></select></label></div><label>Hook idea<input value={hook} onChange={e=>setHook(e.target.value)}/></label><button className="primary" onClick={generate} disabled={loading}><Sparkles/>{loading?"Creating package…":"Build creative package"}</button>{error&&<p className="ai-error">{error}</p>}</section><section className="panel output"><div className="panel-head"><div><small className="label">02 · AI OUTPUT</small><h2>{result?.title||"Ready for Suno"}</h2></div><button onClick={()=>navigator.clipboard.writeText(output)}><Copy/>{copied?"Copied":"Copy"}</button></div>{result?<><p className="rationale">{result.rationale}</p><h3>STYLE PROMPT</h3><pre>{result.stylePrompt}</pre><h3>LYRICS</h3><pre className="lyrics">{result.lyrics}</pre><h3>SHORT HOOKS</h3><ol>{result.hooks.map(x=><li key={x}>{x}</li>)}</ol><h3>EXCLUDE</h3><p className="exclude">{result.excludedStyles}</p></>:<pre>{prompt}</pre>}<div className="checks"><span>● Original lyrics</span><span>● Structured output</span><span>● Suno-ready</span></div></section></div></>}
function ReleasePlan(){const days=["MON 31","TUE 01","WED 02","THU 03","FRI 04","SAT 05","SUN 06"];return <><Title tag="DISTRIBUTION" title="Release plan" text="One song. Multiple intentional moments."/><div className="calendar">{days.map((d,i)=><article key={d}><small>{d}</small>{[0,2,3,5].includes(i)&&<div className="event"><small>{i===3?"RELEASE":"SHORT"}</small><b>{i===3?"Full song + visualizer":"Eindhoven hook cut"}</b><span>19:30 · YouTube</span></div>}</article>)}</div></>}
function Analytics(){return <><Title tag="INTELLIGENCE" title="Analytics" text="See what earns attention before you invest in the next release."/><div className="studio"><section className="panel chart"><div className="panel-head"><div><small className="label">7-DAY PERFORMANCE</small><h2>Audience signal</h2></div><b>+24.8%</b></div><div className="bars">{[22,35,29,51,43,68,82,64,91,75,96,88].map((n,i)=><i key={i} style={{height:n+"%"}}/>)}</div></section><section className="panel insight"><Sparkles/><small className="label">NEXT BEST MOVE</small><h2>Your Tunisian hooks hold attention longer.</h2><p>Keep the first vocal inside 0.7 seconds and test Dutch subtitles on the next three shorts.</p></section></div></>}
