"use client";
import { useMemo, useState } from "react";
import { ArrowLeft, Check, ChevronRight, Copy, Disc3, FileAudio, Play, Plus, Rocket, Sparkles, Upload, WandSparkles } from "lucide-react";

type Project = { id:number; title:string; genre:string; stage:string; score:number };
type Package = { title:string; lyrics:string; stylePrompt:string; excludedStyles:string; hooks:string[]; rationale:string };
const steps=["Brief","Lyrics","Suno versions","Content pack","Release"];
const checklist=["Final master selected","Cover 3000 × 3000","YouTube visualizer","Three vertical shorts","Metadata reviewed","Release date confirmed"];

export default function ProjectStudio({project,onBack}:{project:Project;onBack:()=>void}){
 const [step,setStep]=useState(0),[direction,setDirection]=useState(`An original ${project.genre} song with a powerful memorable chorus.`),[language,setLanguage]=useState("Tunisian"),[hook,setHook]=useState(""),[result,setResult]=useState<Package|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(""),[audio,setAudio]=useState<string|null>(null),[done,setDone]=useState<number[]>([]);
 const progress=useMemo(()=>Math.round(((step+done.length/Math.max(checklist.length,1))/steps.length)*100),[step,done]);
 async function generate(){setLoading(true);setError("");try{const r=await fetch("/api/generate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({direction,language,vocal:"Emotional male",hook})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Generation failed");setResult(d.package);setStep(1);localStorage.setItem(`studio-${project.id}`,JSON.stringify(d.package))}catch(e){setError(e instanceof Error?e.message:"Generation failed")}finally{setLoading(false)}}
 function loadAudio(file?:File){if(!file)return;if(audio)URL.revokeObjectURL(audio);setAudio(URL.createObjectURL(file))}
 return <section className="project-studio">
  <div className="studio-top"><button onClick={onBack}><ArrowLeft/>All projects</button><div className="studio-progress"><span><b style={{width:`${progress}%`}}/></span><small>{progress}% production ready</small></div><button className="publish"><Rocket/>Prepare release</button></div>
  <div className="project-hero"><div className="project-art"><Disc3/></div><div><small className="label">ACTIVE SONG PROJECT</small><h1>{project.title}</h1><p>{project.genre} · Independent release · Score {project.score}</p></div><div className="project-score"><strong>{project.score}</strong><span>OPPORTUNITY</span></div></div>
  <nav className="studio-tabs">{steps.map((x,i)=><button key={x} className={step===i?"active":""} onClick={()=>setStep(i)}><b>{String(i+1).padStart(2,"0")}</b>{x}{i<steps.length-1&&<ChevronRight/>}</button>)}</nav>
  {step===0&&<div className="studio-columns"><section className="studio-card"><small className="label">CREATIVE BRIEF</small><h2>Define the signal.</h2><label>Direction<textarea value={direction} onChange={e=>setDirection(e.target.value)}/></label><div className="field-pair"><label>Language<select value={language} onChange={e=>setLanguage(e.target.value)}><option>Tunisian</option><option>Arabic</option><option>Dutch</option><option>English</option><option>French</option></select></label><label>Target format<select><option>Full song + Shorts</option><option>Short-form hook</option><option>YouTube release</option></select></label></div><label>Hook seed<input value={hook} onChange={e=>setHook(e.target.value)} placeholder="A phrase, emotion or first line…"/></label><button className="studio-primary" onClick={generate} disabled={loading}><WandSparkles/>{loading?"Building your package…":"Generate complete song package"}</button>{error&&<p className="studio-error">{error}</p>}</section><aside className="studio-card brief-side"><Sparkles/><small className="label">AI CREATIVE DIRECTOR</small><h2>One brief becomes a production system.</h2><p>Original lyrics, Suno direction, short-form hooks and release metadata stay connected to this project.</p><ul><li><Check/>Originality guardrails</li><li><Check/>Structured for Suno</li><li><Check/>Built for short-form testing</li></ul></aside></div>}
  {step===1&&<div className="lyrics-layout"><section className="studio-card lyric-editor"><div className="card-title"><div><small className="label">MASTER DRAFT</small><h2>{result?.title||project.title}</h2></div><button onClick={()=>navigator.clipboard.writeText(result?.lyrics||"")}><Copy/>Copy lyrics</button></div><pre>{result?.lyrics||"Generate the creative package from the Brief tab. Your structured lyrics will appear here with Intro, Verses, Chorus, Bridge and Outro."}</pre></section><aside className="studio-card hook-bank"><small className="label">HOOK BANK</small><h2>Short-form tests</h2>{(result?.hooks||["Hook A waiting","Hook B waiting","Hook C waiting"]).map((x,i)=><div className="hook" key={x}><b>0{i+1}</b><p>{x}</p><button><Play/></button></div>)}</aside></div>}
  {step===2&&<div className="studio-columns"><section className="studio-card upload-zone"><small className="label">SUNO VERSIONS</small><h2>Compare before you commit.</h2><label className="drop"><Upload/><strong>Upload an MP3 or WAV version</strong><span>Stored for this session · max depends on your browser</span><input type="file" accept="audio/*" onChange={e=>loadAudio(e.target.files?.[0])}/></label>{audio&&<audio controls src={audio}/>}<button className="ghost"><Plus/>Add another version</button></section><aside className="studio-card prompt-card"><small className="label">SUNO PACKAGE</small><h2>Production direction</h2><h3>STYLE PROMPT</h3><p>{result?.stylePrompt||"Generate your package first to unlock a tailored Suno style prompt."}</p><h3>EXCLUDE</h3><p>{result?.excludedStyles||"No exclusions generated yet."}</p><button onClick={()=>navigator.clipboard.writeText(result?.stylePrompt||"")}><Copy/>Copy for Suno</button></aside></div>}
  {step===3&&<div className="content-pack"><PackCard tag="YOUTUBE" title="Full release" body={`Official visualizer · ${project.title}`} items={["SEO title","Description","Pinned comment"]}/><PackCard tag="SHORT 01" title="The instant hook" body={result?.hooks?.[0]||"Generate a hook from your brief"} items={["15 sec","Fast subtitle","CTA: full song"]}/><PackCard tag="SHORT 02" title="Lyric moment" body={result?.hooks?.[1]||"Second hook variation"} items={["30 sec","Kinetic lyrics","No intro"]}/><PackCard tag="SHORT 03" title="Story cut" body={result?.hooks?.[2]||"Third hook variation"} items={["45 sec","Context first","Loop ending"]}/></div>}
  {step===4&&<div className="release-layout"><section className="studio-card release-check"><small className="label">RELEASE CONTROL</small><h2>Nothing ships half-finished.</h2>{checklist.map((x,i)=><button key={x} onClick={()=>setDone(d=>d.includes(i)?d.filter(n=>n!==i):[...d,i])} className={done.includes(i)?"done":""}><i>{done.includes(i)&&<Check/>}</i><span>{x}</span><small>{done.includes(i)?"READY":"PENDING"}</small></button>)}</section><aside className="studio-card release-summary"><FileAudio/><small className="label">FINAL GATE</small><h2>{done.length}/{checklist.length} ready</h2><p>Complete the checklist, then your files and metadata are ready for YouTube and distribution.</p><div className="big-progress"><b style={{width:`${done.length/checklist.length*100}%`}}/></div><button className="studio-primary" disabled={done.length!==checklist.length}><Rocket/>Mark release ready</button></aside></div>}
 </section>
}
function PackCard({tag,title,body,items}:{tag:string;title:string;body:string;items:string[]}){return <article className="pack-card"><small className="label">{tag}</small><div className="pack-wave">{Array.from({length:24},(_,i)=><i key={i} style={{height:8+(i*13)%34}}/>)}</div><h2>{title}</h2><p>{body}</p><div>{items.map(x=><span key={x}>{x}</span>)}</div><button><Copy/>Copy package</button></article>}
